### ISSUE TITLE
parameters in the model forwarding when training

### ISSUE THREAD

**Issue by rose-jinyang** [PeterL1n/RobustVideoMatting#111]
Hello
How are you?
Thanks for contributing to this project.
I have a question.
I saw that the parameters in the model forwarding are different from the ones when inferencing the model.

In the inference step

![image](https://user-images.githubusercontent.com/47862419/143557289-9322d5d2-740d-448b-9a1d-bc05bdb8d2a8.png)

In the training step

![image](https://user-images.githubusercontent.com/47862419/143557425-9e3586ac-4671-42fa-89d5-56af78abfe91.png)

Could u explain this?
Thanks

**Comment by PeterL1n** [comment]
The model supports both 4-dimensional input [B, C, H, W] and 5-dimensional input [B, T, C, H, W].

For 4-dimensional input, you just provide one frame at a time and recycle the hidden states.

For 5-dimensional input, T consecutive frames are given at once, so that the model can parallelize them on modules that are not ConvGRU layers. The model additionally returns only the recurrent hidden state from the last frame, so you can recycle the hidden state for the next T frame chunk.

At training, the clips are exactly T frame long and they are all fitted onto the GPU, so no need to recycle them. At inference, the video clips are much longer, so we forward T frame at a time and recycle the hidden states. T is controlled by the `seq_chunk` parameter

**Comment by rose-jinyang** [comment]
Thanks for your quick apply.

**Comment by rose-jinyang** [comment]
If seq_chunk == 1, how should be the model forward  changed in the training step?
