### ISSUE TITLE
Question on training scheme

### ISSUE THREAD

**Issue by xianshunw** [PeterL1n/RobustVideoMatting#18]
It seems that the network doesn't use the previous hidden state in training phase:
```
with autocast(enabled=not self.args.disable_mixed_precision):
            pred_fgr, pred_pha = self.model_ddp(true_src, downsample_ratio=downsample_ratio)[:2]
            loss = matting_loss(pred_fgr, pred_pha, true_fgr, true_pha)

self.scaler.scale(loss['total']).backward()
self.scaler.step(self.optimizer)
self.scaler.update()
self.optimizer.zero_grad()
```
But it is fed into the network in the test phase:

```
src = src.to(device, dtype, non_blocking=True).unsqueeze(0) # [B, T, C, H, W]
fgr, pha, *rec = model(src, *rec, downsample_ratio)
```
Why does the network use different feedforward scheme in these two stage.  Will it be better to take the hidden state as input during training stage?

**Comment by PeterL1n** [comment]
The training stage does use recurrent states.

The input `true_src` is a 5-dimensional tensor of shape `[B, T, C, H, W]`. So we provide all the frames directly and the model internally recycles the hidden states.

For inference, you do need to recycle the hidden state yourself, because the videos are too long to fit all frames onto the GPU memory. No matter you are sending 4-dimensional tensor `[B, C, H, W]` frame-by-frame or sending in 5-dimensional frame chunks, you need to recycle the hidden state.

**Comment by xianshunw** [comment]
Got it, thx.
